
package com.osc.ccad.producao.account;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @param processData
     * @param processControl
     * @return
     *     returns com.osc.ccad.producao.account.ProcessData
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/processCSAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "processCSAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.ProcessCSAccount")
    @ResponseWrapper(localName = "processCSAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.ProcessCSAccountResponse")
    public ProcessData processCSAccount(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processData
     * @param processControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/processCSAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processCSAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.ProcessCSAccountAsync")
    public void processCSAccountAsync(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.osc.ccad.producao.account.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.osc.ccad.producao.account.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param partyId
     * @return
     *     returns com.osc.ccad.producao.account.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetAccountResponse")
    public DataObjectResult getAccount(
        @WebParam(name = "PartyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        long partyId)
        throws ServiceException
    ;

    /**
     * 
     * @param account
     * @return
     *     returns com.osc.ccad.producao.account.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/createAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.CreateAccountResponse")
    public DataObjectResult createAccount(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account)
        throws ServiceException
    ;

    /**
     * 
     * @param account
     * @return
     *     returns com.osc.ccad.producao.account.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/updateAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.UpdateAccount")
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.UpdateAccountResponse")
    public DataObjectResult updateAccount(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account)
        throws ServiceException
    ;

    /**
     * 
     * @param account
     * @return
     *     returns com.osc.ccad.producao.account.MethodResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/deleteAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "deleteAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.DeleteAccount")
    @ResponseWrapper(localName = "deleteAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.DeleteAccountResponse")
    public MethodResult deleteAccount(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account)
        throws ServiceException
    ;

    /**
     * 
     * @param account
     * @return
     *     returns com.osc.ccad.producao.account.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/mergeAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "mergeAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.MergeAccount")
    @ResponseWrapper(localName = "mergeAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.MergeAccountResponse")
    public DataObjectResult mergeAccount(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns com.osc.ccad.producao.account.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/findAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "findAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.FindAccount")
    @ResponseWrapper(localName = "findAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.FindAccountResponse")
    public DataObjectResult findAccount(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param changeOperation
     * @param account
     * @return
     *     returns com.osc.ccad.producao.account.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/processAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
    @RequestWrapper(localName = "processAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.ProcessAccount")
    @ResponseWrapper(localName = "processAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.ProcessAccountResponse")
    public DataObjectResult processAccount(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        String changeOperation,
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        List<Account> account,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/findAccountAsync")
    @Oneway
    @RequestWrapper(localName = "findAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.FindAccountAsync")
    public void findAccountAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        FindControl findControl);

    /**
     * 
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/updateAccountAsync")
    @Oneway
    @RequestWrapper(localName = "updateAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.UpdateAccountAsync")
    public void updateAccountAsync(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account);

    /**
     * 
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/createAccountAsync")
    @Oneway
    @RequestWrapper(localName = "createAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.CreateAccountAsync")
    public void createAccountAsync(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account);

    /**
     * 
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/mergeAccountAsync")
    @Oneway
    @RequestWrapper(localName = "mergeAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.MergeAccountAsync")
    public void mergeAccountAsync(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account);

    /**
     * 
     * @param partyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/getAccountAsync")
    @Oneway
    @RequestWrapper(localName = "getAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.GetAccountAsync")
    public void getAccountAsync(
        @WebParam(name = "PartyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        long partyId);

    /**
     * 
     * @param processControl
     * @param changeOperation
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/processAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.ProcessAccountAsync")
    public void processAccountAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        String changeOperation,
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        List<Account> account,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param account
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/deleteAccountAsync")
    @Oneway
    @RequestWrapper(localName = "deleteAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/", className = "com.osc.ccad.producao.account.DeleteAccountAsync")
    public void deleteAccountAsync(
        @WebParam(name = "account", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/accountService/types/")
        Account account);

}
