
package com.rn.tarjab.producao.typed;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RightNowSyncPort", targetNamespace = "urn:wsdl.ws.rightnow.com/v1_3")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RightNowSyncPort {


    /**
     * 
     * @param processingOptions
     * @param requestHeader
     * @param rnObjects
     * @return
     *     returns com.rn.tarjab.producao.typed.RNObjectsResult
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFaultDetail
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "Create", action = "Create")
    @WebResult(name = "RNObjectsResult", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.CreateMsg")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.CreateResponseMsg")
    public RNObjectsResult create(
        @WebParam(name = "RNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> rnObjects,
        @WebParam(name = "ProcessingOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        CreateProcessingOptions processingOptions,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, RequestErrorFaultDetail, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param processingOptions
     * @param requestHeader
     * @param rnObjects
     * @return
     *     returns com.rn.tarjab.producao.typed.RNObjectsResult
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFaultDetail
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "Get", action = "Get")
    @WebResult(name = "RNObjectsResult", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "Get", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMsg")
    @ResponseWrapper(localName = "GetResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetResponseMsg")
    public RNObjectsResult get(
        @WebParam(name = "RNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> rnObjects,
        @WebParam(name = "ProcessingOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        GetProcessingOptions processingOptions,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, RequestErrorFaultDetail, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param processingOptions
     * @param requestHeader
     * @param rnObjects
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFaultDetail
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "Update", action = "Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.UpdateMsg")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.UpdateResponseMsg")
    public void update(
        @WebParam(name = "RNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> rnObjects,
        @WebParam(name = "ProcessingOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        UpdateProcessingOptions processingOptions,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, RequestErrorFaultDetail, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param processingOptions
     * @param requestHeader
     * @param rnObjects
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFaultDetail
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "Destroy", action = "Destroy")
    @RequestWrapper(localName = "Destroy", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.DestroyMsg")
    @ResponseWrapper(localName = "DestroyResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.DestroyResponseMsg")
    public void destroy(
        @WebParam(name = "RNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> rnObjects,
        @WebParam(name = "ProcessingOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        DestroyProcessingOptions processingOptions,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, RequestErrorFaultDetail, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param returnRawResult
     * @param delimiter
     * @param query
     * @param fileData
     * @param pageSize
     * @param requestHeader
     * @param disableMTOM
     * @param csvTableSet
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "QueryCSV", action = "QueryCSV")
    @RequestWrapper(localName = "QueryCSV", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.QueryMsg")
    @ResponseWrapper(localName = "QueryCSVResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.QueryCSVResponseMsg")
    public void queryCSV(
        @WebParam(name = "Query", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String query,
        @WebParam(name = "PageSize", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Integer pageSize,
        @WebParam(name = "Delimiter", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String delimiter,
        @WebParam(name = "ReturnRawResult", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Boolean returnRawResult,
        @WebParam(name = "DisableMTOM", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Boolean disableMTOM,
        @WebParam(name = "CSVTableSet", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", mode = WebParam.Mode.OUT)
        Holder<CSVTableSet> csvTableSet,
        @WebParam(name = "FileData", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", mode = WebParam.Mode.OUT)
        Holder<byte[]> fileData,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param objectTemplates
     * @param query
     * @param pageSize
     * @param requestHeader
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.QueryResultData>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "QueryObjects", action = "QueryObjects")
    @WebResult(name = "Result", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "QueryObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.QueryObjectsMsg")
    @ResponseWrapper(localName = "QueryObjectsResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.QueryObjectsResponseMsg")
    public List<QueryResultData> queryObjects(
        @WebParam(name = "Query", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String query,
        @WebParam(name = "ObjectTemplates", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> objectTemplates,
        @WebParam(name = "PageSize", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Integer pageSize,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param analyticsReport
     * @param returnRawResult
     * @param delimiter
     * @param fileData
     * @param limit
     * @param start
     * @param requestHeader
     * @param disableMTOM
     * @param csvTableSet
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "RunAnalyticsReport", action = "RunAnalyticsReport")
    @RequestWrapper(localName = "RunAnalyticsReport", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.RunAnalyticsReportMsg")
    @ResponseWrapper(localName = "RunAnalyticsReportResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.RunAnalyticsReportResponseMsg")
    public void runAnalyticsReport(
        @WebParam(name = "AnalyticsReport", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        AnalyticsReport analyticsReport,
        @WebParam(name = "Limit", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Integer limit,
        @WebParam(name = "Start", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Integer start,
        @WebParam(name = "Delimiter", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String delimiter,
        @WebParam(name = "ReturnRawResult", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Boolean returnRawResult,
        @WebParam(name = "DisableMTOM", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Boolean disableMTOM,
        @WebParam(name = "CSVTableSet", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", mode = WebParam.Mode.OUT)
        Holder<CSVTableSet> csvTableSet,
        @WebParam(name = "FileData", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", mode = WebParam.Mode.OUT)
        Holder<byte[]> fileData,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param contactID
     * @param campaignID
     * @param requestHeader
     * @param entryPoint
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "ExecuteMarketingFlow", action = "ExecuteMarketingFlow")
    @RequestWrapper(localName = "ExecuteMarketingFlow", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ExecuteMarketingFlowMsg")
    @ResponseWrapper(localName = "ExecuteMarketingFlowResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ExecuteMarketingFlowResponseMsg")
    public void executeMarketingFlow(
        @WebParam(name = "ContactID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID contactID,
        @WebParam(name = "CampaignID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID campaignID,
        @WebParam(name = "EntryPoint", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String entryPoint,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param rnObject
     * @param requestHeader
     * @param disableMTOM
     * @param fileID
     * @return
     *     returns byte[]
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetFileData", action = "GetFileData")
    @WebResult(name = "FileData", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetFileData", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetFileDataMsg")
    @ResponseWrapper(localName = "GetFileDataResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetFileDataResponseMsg")
    public byte[] getFileData(
        @WebParam(name = "RNObject", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        RNObject rnObject,
        @WebParam(name = "FileID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID fileID,
        @WebParam(name = "DisableMTOM", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        Boolean disableMTOM,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param contactID
     * @param requestHeader
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "ResetContactPassword", action = "ResetContactPassword")
    @RequestWrapper(localName = "ResetContactPassword", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ResetContactPasswordMsg")
    @ResponseWrapper(localName = "ResetContactPasswordResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ResetContactPasswordResponseMsg")
    public void resetContactPassword(
        @WebParam(name = "ContactID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID contactID,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param opportunityID
     * @param scheduledTime
     * @param chatID
     * @param contactID
     * @param requestHeader
     * @param mailingID
     * @param incidentID
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "SendMailingToContact", action = "SendMailingToContact")
    @RequestWrapper(localName = "SendMailingToContact", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.SendMailingToContactMsg")
    @ResponseWrapper(localName = "SendMailingToContactResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.SendMailingToContactResponseMsg")
    public void sendMailingToContact(
        @WebParam(name = "ContactID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID contactID,
        @WebParam(name = "MailingID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID mailingID,
        @WebParam(name = "ScheduledTime", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        XMLGregorianCalendar scheduledTime,
        @WebParam(name = "IncidentID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID incidentID,
        @WebParam(name = "OpportunityID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID opportunityID,
        @WebParam(name = "ChatID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        ID chatID,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param destinationRNObject
     * @param sourceRNObjects
     * @param requestHeader
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "TransferSubObjects", action = "TransferSubObjects")
    @RequestWrapper(localName = "TransferSubObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.TransferSubObjectsMsg")
    @ResponseWrapper(localName = "TransferSubObjectsResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.TransferSubObjectsResponseMsg")
    public void transferSubObjects(
        @WebParam(name = "DestinationRNObject", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        RNObject destinationRNObject,
        @WebParam(name = "SourceRNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> sourceRNObjects,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.SubscribableObject>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetSubscribableObjects", action = "GetSubscribableObjects")
    @WebResult(name = "SubscribableObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetSubscribableObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetSubscribableObjectsMsg")
    @ResponseWrapper(localName = "GetSubscribableObjectsResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetSubscribableObjectsResponseMsg")
    public List<SubscribableObject> getSubscribableObjects(
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param batchRequestItem
     * @param requestHeader
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.BatchResponseItem>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFaultDetail
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "Batch", action = "Batch")
    @WebResult(name = "BatchResponseItem", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "Batch", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.BatchMsg")
    @ResponseWrapper(localName = "BatchResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.BatchResponseMsg")
    public List<BatchResponseItem> batch(
        @WebParam(name = "BatchRequestItem", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<BatchRequestItem> batchRequestItem,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, RequestErrorFaultDetail, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @param rnObjects
     * @return
     *     returns com.rn.tarjab.producao.typed.RNObjectsResult
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "ConvertGenericToObject", action = "ConvertGenericToObject")
    @WebResult(name = "RNObjectsResult", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "ConvertGenericToObject", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ConvertObjectMsg")
    @ResponseWrapper(localName = "ConvertGenericToObjectResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ConvertObjectResponseMsg")
    public RNObjectsResult convertGenericToObject(
        @WebParam(name = "RNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> rnObjects,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @param rnObjects
     * @return
     *     returns com.rn.tarjab.producao.typed.RNObjectsResult
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "ConvertObjectToGeneric", action = "ConvertObjectToGeneric")
    @WebResult(name = "RNObjectsResult", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "ConvertObjectToGeneric", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ConvertObjectMsg")
    @ResponseWrapper(localName = "ConvertObjectToGenericResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.ConvertObjectResponseMsg")
    public RNObjectsResult convertObjectToGeneric(
        @WebParam(name = "RNObjects", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObject> rnObjects,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.MetaDataClass>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetMetaData", action = "GetMetaData")
    @WebResult(name = "MetaDataClass", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetMetaData", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataMsg")
    @ResponseWrapper(localName = "GetMetaDataResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataResponseMsg")
    public List<MetaDataClass> getMetaData(
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param metaDataLink
     * @param className
     * @param requestHeader
     * @param qualifiedClassName
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.MetaDataClass>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetMetaDataForClass", action = "GetMetaDataForClass")
    @WebResult(name = "MetaDataClass", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetMetaDataForClass", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataForClassMsg")
    @ResponseWrapper(localName = "GetMetaDataForClassResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataForClassResponseMsg")
    public List<MetaDataClass> getMetaDataForClass(
        @WebParam(name = "ClassName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<String> className,
        @WebParam(name = "QualifiedClassName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObjectType> qualifiedClassName,
        @WebParam(name = "MetaDataLink", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<String> metaDataLink,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param className
     * @param requestHeader
     * @param qualifiedClassName
     * @param operation
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.MetaDataClassOperation>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetMetaDataForOperation", action = "GetMetaDataForOperation")
    @WebResult(name = "MetaDataClassOperation", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetMetaDataForOperation", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataForOperationMsg")
    @ResponseWrapper(localName = "GetMetaDataForOperationResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataForOperationResponseMsg")
    public List<MetaDataClassOperation> getMetaDataForOperation(
        @WebParam(name = "Operation", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<String> operation,
        @WebParam(name = "ClassName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<String> className,
        @WebParam(name = "QualifiedClassName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        List<RNObjectType> qualifiedClassName,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetMetaDataLastChangeTime", action = "GetMetaDataLastChangeTime")
    @WebResult(name = "LastChangeDateTime", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetMetaDataLastChangeTime", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataLastChangeTimeMsg")
    @ResponseWrapper(localName = "GetMetaDataLastChangeTimeResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetMetaDataLastChangeTimeResponseMsg")
    public XMLGregorianCalendar getMetaDataLastChangeTime(
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.RNObjectType>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetPrimaryClassNames", action = "GetPrimaryClassNames")
    @WebResult(name = "PrimaryClassName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetPrimaryClassNames", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetPrimaryClassNamesMsg")
    @ResponseWrapper(localName = "GetPrimaryClassNamesResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetPrimaryClassNamesResponseMsg")
    public List<RNObjectType> getPrimaryClassNames(
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param fieldName
     * @param requestHeader
     * @param packageName
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.NamedID>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetValuesForNamedID", action = "GetValuesForNamedID")
    @WebResult(name = "Entry", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetValuesForNamedID", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetValuesForNamedIDMsg")
    @ResponseWrapper(localName = "GetValuesForNamedIDResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetValuesForNamedIDResponseMsg")
    public List<NamedID> getValuesForNamedID(
        @WebParam(name = "PackageName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String packageName,
        @WebParam(name = "FieldName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String fieldName,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param fieldName
     * @param requestHeader
     * @return
     *     returns java.util.List<com.rn.tarjab.producao.typed.NamedIDWithParent>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetValuesForNamedIDHierarchy", action = "GetValuesForNamedIDHierarchy")
    @WebResult(name = "Entry", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
    @RequestWrapper(localName = "GetValuesForNamedIDHierarchy", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetValuesForNamedIDHierarchyMsg")
    @ResponseWrapper(localName = "GetValuesForNamedIDHierarchyResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", className = "com.rn.tarjab.producao.typed.GetValuesForNamedIDHierarchyResponseMsg")
    public List<NamedIDWithParent> getValuesForNamedIDHierarchy(
        @WebParam(name = "FieldName", targetNamespace = "urn:messages.ws.rightnow.com/v1_3")
        String fieldName,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1_3", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

}
